//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyPick
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
